import {chromium,request} from '@playwright/test';
import {PrismaClient} from '@prisma/client';
import bcrypt from 'bcryptjs';
import {randomUUID} from 'node:crypto';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const target=new URL(process.env.DATABASE_URL||'');
if(target.hostname!=='127.0.0.1'||target.port!=='55432'||target.pathname!=='/op_boosters_test')throw Error('Isolated database required');
const db=new PrismaClient(),baseURL='http://localhost:3007',results=[];let browser;
const evidence=new URL('../../docs/design/evidence/phase-6-pwa/',import.meta.url);fs.mkdirSync(evidence,{recursive:true});
async function check(name,fn){try{await fn();results.push({name,status:'PASS'});}catch(e){results.push({name,status:'FAIL',detail:e.message});}console.log(results.at(-1));}
try{
 const password='Mobile-Pages-9!',tag=randomUUID(),setCode=`EB-${Date.now()}`;
 const user=await db.user.create({data:{name:'Mugiwara fixture',email:`mobile-pages-${tag}@example.test`,password:await bcrypt.hash(password,10),hasStarterDecks:true}});
 const other=await db.user.create({data:{name:'Other fixture',email:`mobile-other-${tag}@example.test`,password:await bcrypt.hash(password,10),hasStarterDecks:true}});
 await db.cardSet.create({data:{code:setCode,name:'Escales mobiles fixture',releaseDate:new Date()}});
 const cards=[];for(let i=0;i<4;i++)cards.push(await db.card.create({data:{id:`pages-${tag}-${i}`,code:`PAGES-${i}`,name:`Carte escale ${i}`,setCode,set:setCode,type:'CHARACTER',color:'RED',rarity:i===3?'SR':'C',cost:3,power:5000,imageUrl:'/images/OP05-119.webp'}}));
 await db.userCard.create({data:{userId:user.id,cardId:cards[0].id,quantity:3}});await db.userCard.create({data:{userId:user.id,cardId:cards[1].id,quantity:2}});
 await db.setRules.create({data:{code:setCode,rarityCounts:{},typeCounts:{},boosterRules:{version:1,label:'Fixture mobile 2 cartes',source:'Test isolé uniquement',slots:[{choices:[{rarity:'C',weight:1,variant:'any'}]},{choices:[{rarity:'C',weight:1,variant:'any'}]}],specialPacks:[]}}});
 async function login(account){const api=await request.newContext({baseURL});const csrf=await(await api.get('/api/auth/csrf')).json();await api.post('/api/auth/callback/credentials',{form:{email:account.email,password,csrfToken:csrf.csrfToken,callbackUrl:baseURL},maxRedirects:0});assert.equal((await(await api.get('/api/auth/session')).json()).user.id,account.id);return api;}
 const api=await login(user),bob=await login(other);
 const opened=await api.post('/api/booster/open',{data:{setCode,idempotencyKey:randomUUID()}});assert.equal(opened.status(),201);const opening=(await opened.json()).opening;const before=await db.userCard.aggregate({where:{userId:user.id},_sum:{quantity:true}});const unique=await db.userCard.count({where:{userId:user.id}});
 browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const context=await browser.newContext({storageState:await api.storageState(),viewport:{width:390,height:844},colorScheme:'dark'});const page=await context.newPage();page.setDefaultTimeout(15000);const errors=[];page.on('pageerror',e=>errors.push(e.message));let posts=0;page.on('request',r=>{if(r.method()==='POST'&&r.url().includes('/api/booster'))posts++;});
 await check('Compact home uses real unique/copy/deck statistics and three mobile tiles',async()=>{
  await page.goto(baseURL+'/home');await page.getByRole('region',{name:'Statistiques de collection'}).waitFor();assert.equal(await page.locator('.piece-stats .piece-stat:visible').count(),3);const text=await page.locator('.piece-stat-collection').textContent();assert.ok(text.includes(`${unique}`));assert.ok(text.includes(`${before._sum.quantity} exemplaires`));assert.equal(await page.getByRole('link',{name:'Ouvrir un booster',exact:true}).first().getAttribute('href'),'/boosters');await page.locator('.piece-recent-strip .piece-card').first().waitFor();
 });
 await check('Mobile history opens recorded result, nested card and closes back to row without credit',async()=>{
  await page.goto(baseURL+'/history');await page.locator('.piece-history-row').first().click();await page.getByRole('dialog').getByRole('heading',{name:'Résultat de l’ouverture',exact:true}).waitFor();assert.equal(await page.locator('.piece-history-receipt .piece-card').count(),2);await page.locator('.piece-history-receipt .piece-card').first().click();await page.getByRole('button',{name:'Agrandir l’illustration',exact:true}).waitFor();await page.keyboard.press('Escape');await page.getByRole('heading',{name:'Résultat de l’ouverture',exact:true}).waitFor();await page.screenshot({path:new URL('history-result-mobile.png',evidence).pathname,animations:'disabled'});await page.keyboard.press('Escape');await page.getByRole('dialog').waitFor({state:'hidden'});assert.equal(await page.locator('.piece-history-row').first().evaluate(el=>el===document.activeElement),true);await page.goto(`${baseURL}/history?opening=${opening.id}`);await page.locator('.piece-history-receipt .piece-card').first().waitFor();await page.reload();await page.locator('.piece-history-receipt .piece-card').first().waitFor();assert.equal(posts,0);assert.equal((await db.userCard.aggregate({where:{userId:user.id},_sum:{quantity:true}}))._sum.quantity,before._sum.quantity);
 });
 await check('Private receipts refuse another user and history is no-store',async()=>{
  assert.equal((await bob.get(`/api/booster/openings/${opening.id}`)).status(),404);assert.match((await api.get('/api/booster/history')).headers()['cache-control'],/no-store/);
 });
 await check('Extension progression links to only missing cards of the selected real set',async()=>{
  await page.goto(baseURL+'/progress');await page.getByRole('searchbox',{name:'Rechercher une extension',exact:true}).fill(setCode);await page.waitForFunction(()=>document.querySelectorAll('.piece-progress-entry').length===1);assert.ok((await page.locator('.piece-progress-entry').textContent()).includes(`${unique} / 4 cartes uniques`));await page.getByRole('link',{name:'Voir les cartes manquantes',exact:true}).click();await page.locator('.piece-card').first().waitFor();assert.equal(await page.getByRole('combobox',{name:'Afficher',exact:true}).inputValue(),'missing');assert.equal(await page.locator('.piece-card').count(),4-unique);assert.ok((await page.locator('.piece-card-code').allTextContents()).every(text=>text.includes('PAGES-')));
 });
 await check('Profile preferences persist independently and installation guidance is accessible',async()=>{
  await page.goto(baseURL+'/profile');await page.getByLabel('Vibrations de révélation (si disponibles)',{exact:true}).check();await page.getByLabel('Cinématiques d’ouverture',{exact:true}).uncheck();await page.getByLabel('Réduire les effets visuels',{exact:true}).check();await page.getByLabel('Sons de révélation',{exact:true}).uncheck();await page.reload();await page.waitForFunction(()=>{const input=document.querySelector('input[type=checkbox]');return input && !input.disabled});assert.equal(await page.getByLabel('Vibrations de révélation (si disponibles)',{exact:true}).isChecked(),true);assert.equal(await page.getByLabel('Cinématiques d’ouverture',{exact:true}).isChecked(),false);assert.equal(await page.getByLabel('Sons de révélation',{exact:true}).isChecked(),false);assert.equal(await page.getByLabel('Réduire les effets visuels',{exact:true}).isChecked(),true);await page.getByText('Installer Mugiwara sur mon appareil',{exact:true}).click();await page.getByText(/L’installation dépend du navigateur/).waitFor();
 });
 await check('Preferences wait for identity and never write the guest key for an authenticated account',async()=>{
  await page.route('**/api/auth/session',async route=>{await new Promise(resolve=>setTimeout(resolve,1200));await route.continue()});await page.goto(baseURL+'/profile');const vibration=page.getByLabel('Vibrations de révélation (si disponibles)',{exact:true});await vibration.waitFor();assert.equal(await vibration.isDisabled(),true);await page.waitForFunction(()=>{const input=document.querySelector('input[type=checkbox]');return input && !input.disabled});await vibration.uncheck();await vibration.check();assert.equal(await page.evaluate(()=>localStorage.getItem('mugiwara:display:guest')),null);assert.equal(await page.evaluate(id=>JSON.parse(localStorage.getItem(`mugiwara:display:${id}`)).vibrations,user.id),true);await page.unrouteAll({behavior:'wait'});
 });
 await check('Home history profile progress are responsive at seven viewports',async()=>{
  for(const [width,height] of [[360,800],[375,667],[390,844],[430,932],[768,1024],[1280,800],[1440,900]]){await page.setViewportSize({width,height});for(const route of ['home','history','profile','progress']){await page.goto(`${baseURL}/${route}`);await page.locator('.piece-page').waitFor();if(route==='home')await page.getByRole('region',{name:'Statistiques de collection'}).waitFor();else if(route==='history')await page.locator('.piece-history-row').first().waitFor();else if(route==='progress')await page.locator('.piece-progress-entry').first().waitFor();else await page.getByText('Membre depuis',{exact:true}).waitFor();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${route} ${width}`);if(width===390 || width===1440)await page.screenshot({path:new URL(`${route}-${width}-dark.png`,evidence).pathname,fullPage:true,animations:'disabled'});}}
 });
 await check('Light theme pages and browser theme color follow the chosen preference',async()=>{
  await page.locator('.piece-sidebar-theme').getByRole('button',{name:'Clair',exact:true}).click();await page.waitForFunction(()=>document.documentElement.classList.contains('light'));assert.ok((await page.locator('meta[name="theme-color"]').evaluateAll(nodes=>nodes.map(n=>n.content))).every(value=>value==='#F8F6F0'));for(const route of ['home','history','profile','progress']){await page.setViewportSize({width:390,height:844});await page.goto(`${baseURL}/${route}`);await page.locator('.piece-page').waitFor();await page.screenshot({path:new URL(`${route}-390-light.png`,evidence).pathname,fullPage:true,animations:'disabled'});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
 });
 await check('Manifest assets and real service worker cache only public allowlist',async()=>{
  const manifest=await(await api.get('/manifest.json')).json();assert.equal(manifest.display,'standalone');assert.equal(manifest.short_name,'Mugiwara');for(const icon of manifest.icons)assert.equal((await api.get(icon.src)).status(),200);await page.evaluate(async()=>{await navigator.serviceWorker.ready});await page.waitForFunction(()=>navigator.serviceWorker.controller!==null);await page.goto(baseURL+'/profile');await page.getByText('Membre depuis',{exact:true}).waitFor();const entries=await page.evaluate(async()=>{const result=[];for(const name of await caches.keys())for(const request of await(await caches.open(name)).keys())result.push(new URL(request.url).pathname);return result});assert.deepEqual(entries.sort(),['/offline.html','/images/icons/icon-192.png','/images/icons/icon-512.png','/images/icons/maskable-512.png'].sort());
 });
 await check('Offline private navigation shows generic fallback without personal content',async()=>{
  await context.setOffline(true);await page.goto(baseURL+'/profile');await page.getByRole('heading',{name:'Le signal s’est perdu en mer.',exact:true}).waitFor();assert.equal(await page.getByText(user.email,{exact:true}).count(),0);assert.equal(await page.getByRole('button',{name:'Se déconnecter',exact:true}).count(),0);await page.screenshot({path:new URL('offline-mobile.png',evidence).pathname,animations:'disabled'});await context.setOffline(false);await page.getByRole('link',{name:'Réessayer la connexion',exact:true}).click();await page.getByRole('region',{name:'Statistiques de collection'}).waitFor();
 });
 await check('Install prompt UI and iOS manual guidance use supported paths',async()=>{
  await page.goto(baseURL+'/profile');await page.getByText('Membre depuis',{exact:true}).waitFor();
  await page.evaluate(()=>{window.__installCalls=0;const event=new Event('beforeinstallprompt',{cancelable:true});Object.defineProperties(event,{prompt:{value:async()=>{window.__installCalls++}},userChoice:{value:Promise.resolve({outcome:'accepted'})}});window.dispatchEvent(event)});
  await page.getByRole('button',{name:'Installer',exact:true}).click();assert.equal(await page.evaluate(()=>window.__installCalls),1);
  const ios=await browser.newContext({storageState:await api.storageState(),viewport:{width:390,height:844},userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1'});const safari=await ios.newPage();safari.setDefaultTimeout(15000);await safari.goto(baseURL+'/profile');if(await safari.getByRole('button',{name:'Reporter la mise à jour',exact:true}).isVisible())await safari.getByRole('button',{name:'Reporter la mise à jour',exact:true}).click();await safari.getByText('Installer Mugiwara sur mon appareil',{exact:true}).click();await safari.getByText(/Dans Safari, ouvrez Partager/).waitFor();await ios.close();
 });
 await check('Update UI refuses an unconfirmed intent and requires explicit activation',async()=>{
  const update=await browser.newContext({storageState:await api.storageState(),viewport:{width:390,height:844}});
  await update.addInitScript(()=>{window.__updateMessages=[];Object.defineProperty(navigator.serviceWorker,'controller',{value:{}});Object.defineProperty(navigator.serviceWorker,'register',{value:async()=>Object.assign(new EventTarget(),{waiting:{state:'installed',postMessage:data=>window.__updateMessages.push(data)},installing:null})})});const updating=await update.newPage();await updating.goto(baseURL+'/profile');await updating.getByText('Membre depuis',{exact:true}).waitFor();await updating.getByRole('button',{name:'Mettre à jour',exact:true}).waitFor();
  await updating.evaluate(({id,code})=>sessionStorage.setItem(`op:booster:${id}`,JSON.stringify({setCode:code,idempotencyKey:'test-unconfirmed-key'})),{id:user.id,code:setCode});await updating.getByRole('button',{name:'Mettre à jour',exact:true}).click();await updating.getByText('Une ouverture reste à confirmer. Récupérez-la avant de mettre à jour.',{exact:true}).waitFor();assert.equal(await updating.evaluate(()=>window.__updateMessages.length),0);
  await updating.evaluate(id=>sessionStorage.removeItem(`op:booster:${id}`),user.id);await updating.getByRole('button',{name:'Mettre à jour',exact:true}).click();assert.equal(await updating.evaluate(()=>window.__updateMessages.length),1);await updating.evaluate(()=>{history.pushState({},'', '/booster-opening');navigator.serviceWorker.dispatchEvent(new Event('controllerchange'))});await updating.getByText('Membre depuis',{exact:true}).waitFor();assert.equal(new URL(updating.url()).pathname,'/booster-opening');await update.close();
 });
 await check('No JavaScript errors or extra rewards across mobile pages',async()=>{assert.deepEqual(errors,[]);assert.equal(posts,0);assert.equal(await db.boosterOpening.count({where:{userId:user.id}}),1);assert.equal((await db.userCard.aggregate({where:{userId:user.id},_sum:{quantity:true}}))._sum.quantity,before._sum.quantity);});
 await context.close();await api.dispose();await bob.dispose();
}catch(e){results.push({name:'Mobile pages/PWA setup',status:'FAIL',detail:e.message});}
finally{if(browser)await browser.close();await db.$disconnect();fs.writeFileSync(new URL('results.json',evidence),JSON.stringify(results,null,2));}
if(results.some(r=>r.status==='FAIL'))process.exitCode=1;
